export const keywords = [
  "Next.js",
  "React",
  "JavaScript",
  "Code",
  "Coding",
  "Programming",
  "Web Development",
  "Frontend",
  "Backend",
  "Fullstack",
  "Software Engineering",
  "Tech",
  "Technology",
  "Community",
  "Forum",
  "Q&A",
  "Questions",
  "Answers",
  "Help",
  "Support",
  "Ask",
  "Question",
  "Get Help",
  "Get Answers",
  "Get Support",
  "Get Help with Code",
  "Get Answers to Coding Questions",
  "Get Support with Code",
  "Get Help with Programming",
  "Get Answers to Programming Questions",
  "Get Support with Programming",
  "Get Help with Web Development",
  "Get Answers to Web Development Questions",
  "Get Support with Web Development",
  "Get Help with Software Engineering",
  "Get Answers to Software Engineering Questions",
  "Get Support with Software Engineering",
  "Get Help with Tech",
  "Get Answers to Tech Questions",
  "Get Support with Tech",
  "Get Help with Technology",
  "Get Answers to Technology Questions",
  "Get Support with Technology",
  "Get Help with Next.js",
  "Get Answers to Next.js Questions",
  "Get Support with Next.js",
  "Get Help with React",
  "Get Answers to React Questions",
  "Get Support with React",
  "Get Help with JavaScript",
  "Get Answers to JavaScript Questions",
  "Get Support with JavaScript",
  "Get Help with CodeLounge",
];
